(() => {
  const shell = window.__feedScrollerShared__?.shell;
  if (!shell) return;

  shell.registerSite({
    cssVars: {
      "--arc-jk-progress-offset": "-30px",
    },
    exportName: "__arcJK",
    feed: {
      defaultProfile: "home",
      profileByScopeKey: {
        following: "following",
      },
      profiles: {
        following: {
          container: {
            candidateSelector: "div",
            dominantTagName: "DIV",
            dominantTagRatio: 0.6,
            minimumChildren: 2,
            minimumMatches: 2,
            searchRootSelector: "main",
            xpaths: [
              "/html/body/div[1]/div/div/div/div/div/main/div[2]/div/div/div/div[2]/div/div[5]/div/div[1]/div/div[2]/div",
              "/html/body/div[1]/div/div/div/div/div/main/div[2]/div/div/div/div[2]/div/div[6]/div/div[1]/div/div[2]/div",
            ],
          },
          itemId: {
            mode: "normalized-anchor-href",
          },
          items: {
            childTagName: "DIV",
            mode: "direct-children",
          },
          match: {
            anySelectors: [
              '[data-testid="contentHider-post"]',
              '[data-testid="postText"]',
              '[data-testid="replyBtn"]',
              '[data-testid="likeBtn"]',
              '[data-testid="postShareBtn"]',
              '[data-testid="postDropdownBtn"]',
              '[data-testid="postBookmarkBtn"]',
            ],
            requirePermalink: true,
          },
          permalink: {
            allowTextLengthMax: 12,
            allowTextLengthMin: 1,
            attributeBonuses: {
              "aria-label": 100,
              "data-tooltip": 60,
            },
            depthPenaltyMax: 60,
            depthPenaltyMultiplier: 4,
            hrefIncludes: "/post/",
            hrefLengthPenaltyDivisor: 50,
            hrefLengthPenaltyMax: 10,
            normalizedHrefPattern: "^/profile/[^/]+/post/[^/?#]+",
            requireAnyAttributeNames: ["data-tooltip", "aria-label"],
            roleLinkBonus: 20,
            selector: 'a[href*="/post/"]',
            shortTextBonus: 10,
            shortTextMaxLength: 8,
            topOffsetPenaltyMax: 160,
            topOffsetPenaltyMultiplier: 1,
          },
        },
        home: {
          container: {
            candidateSelector: "div",
            dominantTagName: "DIV",
            dominantTagRatio: 0.6,
            minimumChildren: 2,
            minimumMatches: 2,
            searchRootSelector: "main",
            xpaths: [
              "/html/body/div[1]/div/div/div/div/div/main/div[2]/div/div/div/div[2]/div/div[6]/div/div[1]/div/div[2]/div",
            ],
          },
          itemId: {
            mode: "normalized-anchor-href",
          },
          items: {
            childTagName: "DIV",
            mode: "direct-children",
          },
          match: {
            anySelectors: [],
            requirePermalink: true,
          },
          permalink: {
            attributeBonuses: {
              "aria-label": 100,
              "data-tooltip": 60,
            },
            hrefIncludes: "/post/",
            hrefLengthPenaltyDivisor: 50,
            hrefLengthPenaltyMax: 10,
            roleLinkBonus: 20,
            selector: 'a[href*="/post/"]',
            shortTextBonus: 10,
            shortTextMaxLength: 8,
          },
        },
      },
    },
    flags: {
      enableAfterSyncHandler: false,
      enableArticleAncestorItems: false,
      enableAttributeItemId: false,
      enableBoundaryIdProgressTracking: false,
      enableBottomJumpRestore: false,
      enableCollapseNonHeaderContent: false,
      enableContainerCandidateSearch: true,
      enableContainerXPathLookup: true,
      enableDirectChildItems: true,
      enableDocumentBottomRestore: true,
      enableFallbackTabSelector: true,
      enableFeedMutationObserver: false,
      enableGlobalScopeFallback: true,
      enableHistoryResync: true,
      enableInlineItemLayoutFixes: false,
      enableInlineRenderer: true,
      enableInteractionOnlyWhenRestoreAllowed: false,
      enableItemMarkerValidation: true,
      enableLoadMoreRestore: false,
      enableMutationResync: true,
      enableNormalizedHrefItemId: true,
      enableOverlayRenderer: false,
      enablePathRouteGate: false,
      enablePendingScopeWhenTabsUnavailable: true,
      enablePermalinkProximityBonus: true,
      enablePermalinkSelection: true,
      enablePermalinkValidation: true,
      enablePrimaryTabProgressBlock: true,
      enableProfileByScopeKey: true,
      enableRegexItemId: false,
      enableRestoreDelay: false,
      enableRestoreMissingItemHandler: false,
      enableRestorePauseAfterGrowth: false,
      enableSingleFixedScope: false,
      enableTabAriaActiveState: true,
      enableTabClickResync: true,
      enableTabContainerAncestorLookup: true,
      enableTabContainerTextMatchLookup: false,
      enableTabContainerXPathLookup: true,
      enableTabbedScope: true,
      enableTabIndicatorActiveState: true,
      enableTabTextColorActiveState: true,
      enableUnknownScopeWhenActiveTabMissing: true,
      enableXPathSnapshotItems: false,
    },
    installFlag: "__arcJKBoostInstalled",
    match: {
      allowSubdomains: false,
      domains: ["bsky.app"],
      stripWww: true,
    },
    name: "bluesky",
    restore: {
      maxSteps: 200,
      readinessRequiresContainer: true,
      startDelayMs: 50,
      stopWhenStuckAtOrAbove: true,
      stuckLimit: 10,
      tickMs: 80,
    },
    scope: {
      globalFallback: {
        allowsPersistence: true,
        allowsRestore: true,
        key: "global",
        kind: "global",
        label: "global",
      },
      kind: "home-tab",
      pendingFallback: {
        allowsPersistence: false,
        allowsRestore: false,
        key: "pending",
        kind: "home-tab",
        label: "pending",
      },
      pendingPath: "/",
      unknownFallback: {
        allowsPersistence: false,
        allowsRestore: false,
        key: "unknown",
        kind: "home-tab",
        label: "unknown",
      },
    },
    storageKey: "arc-jk-progress-href-v1",
    tabs: {
      activeSources: [
        { target: "tab", type: "aria-selected" },
        { labelSource: "named-node", type: "aria-selected" },
        {
          labelSource: "named-node",
          type: "indicator-active",
          useLastElementChild: true,
        },
        {
          labelSource: "named-node",
          minChannel: 235,
          type: "text-color-min",
        },
      ],
      container: {
        ancestorStopSelector: "body",
        minimumCount: 2,
        primaryTabSelector:
          '[role="tab"][data-testid^="homeScreenFeedTabs-selector-"]',
        searchRootSelector: "main",
        xpaths: [
          "/html/body/div[1]/div/div/div/div/div/main/div[2]/div/div/div/div[2]/div/div[3]/div/div[1]/div",
        ],
      },
      fallbackTabSelector: "[tabindex]",
      labelSources: [
        {
          attribute: "data-testid",
          key: "named-node",
          preferTestIdSuffix: true,
          rejectIncludes: ["selector-"],
          selector: '[data-testid^="homeScreenFeedTabs-"]',
          testIdPrefix: "homeScreenFeedTabs-",
          text: true,
        },
        {
          key: "dir-auto",
          selector: '[dir="auto"]',
          text: true,
        },
        {
          key: "self",
          selfText: true,
        },
      ],
      minimumCount: 2,
      primaryTabIndex: 0,
      tabSelector: '[role="tab"]',
    },
  });
})();
