(() => {
  const shell = window.__feedScrollerShared__?.shell;
  if (!shell) return;

  shell.registerSite({
    cssVars: {
      "--arc-jk-item-overflow": "visible",
      "--arc-jk-progress-offset": "-24px",
    },
    exportName: "__arcJKLetterboxd",
    feed: {
      defaultProfile: "activity",
      profiles: {
        activity: {
          container: {
            xpaths: ["/html/body/div[1]/div/div/section/div[2]/div"],
          },
          itemId: {
            attributeName: "data-activity-id",
            mode: "attribute",
          },
          items: {
            mode: "xpath-snapshot",
            xpath: "/html/body/div[1]/div/div/section/div[2]/div/section",
          },
        },
      },
    },
    flags: {
      enableAfterSyncHandler: false,
      enableArticleAncestorItems: false,
      enableAttributeItemId: true,
      enableBoundaryIdProgressTracking: false,
      enableBottomJumpRestore: false,
      enableCollapseNonHeaderContent: false,
      enableContainerCandidateSearch: false,
      enableContainerXPathLookup: true,
      enableDirectChildItems: false,
      enableDocumentBottomRestore: false,
      enableFallbackTabSelector: false,
      enableFeedMutationObserver: true,
      enableGlobalScopeFallback: false,
      enableHistoryResync: false,
      enableInlineItemLayoutFixes: true,
      enableInlineRenderer: true,
      enableInteractionOnlyWhenRestoreAllowed: false,
      enableItemMarkerValidation: false,
      enableLoadMoreRestore: true,
      enableMutationResync: false,
      enableNormalizedHrefItemId: false,
      enableOverlayRenderer: false,
      enablePathRouteGate: true,
      enablePendingScopeWhenTabsUnavailable: false,
      enablePermalinkProximityBonus: false,
      enablePermalinkSelection: false,
      enablePermalinkValidation: false,
      enablePrimaryTabProgressBlock: false,
      enableProfileByScopeKey: false,
      enableRegexItemId: false,
      enableRestoreDelay: false,
      enableRestoreMissingItemHandler: false,
      enableRestorePauseAfterGrowth: false,
      enableSingleFixedScope: true,
      enableTabAriaActiveState: false,
      enableTabClickResync: false,
      enableTabContainerAncestorLookup: false,
      enableTabContainerTextMatchLookup: false,
      enableTabContainerXPathLookup: false,
      enableTabbedScope: false,
      enableTabIndicatorActiveState: false,
      enableTabTextColorActiveState: false,
      enableUnknownScopeWhenActiveTabMissing: false,
      enableXPathSnapshotItems: true,
    },
    installFlag: "__arcJKLetterboxdInstalled",
    match: {
      allowSubdomains: true,
      domains: ["letterboxd.com"],
    },
    name: "letterboxd",
    observer: {
      childList: true,
      containerXPath: "/html/body/div[1]/div/div/section/div[2]/div",
      subtree: false,
    },
    render: {
      inlineFixes: {
        checkboxLeft: "var(--arc-jk-progress-offset)",
        checkboxPosition: "absolute",
        checkboxTop: "50%",
        checkboxTransform: "translateY(-50%)",
        itemOverflowImportant: true,
        itemOverflowValue: "visible",
        itemPosition: "relative",
      },
    },
    restore: {
      buttonXPath: "/html/body/div[1]/div/div/section/div[3]/div/a",
      clickThrottleMs: 900,
      maxSteps: 260,
      readinessRequiresContainer: true,
      scrollToBottomFirst: true,
      startDelayMs: 60,
      stuckLimit: 12,
      tickMs: 260,
    },
    route: {
      exactPath: "/activity",
    },
    scope: {
      fixed: {
        allowsPersistence: true,
        allowsRestore: true,
        key: "activity",
        kind: "activity-tab",
        label: "Activity",
      },
      kind: "activity-tab",
    },
    storageKey: "arc-jk-letterboxd-progress-activity-id-v1",
  });
})();
