(() => {
  const shell = window.__feedScrollerShared__?.shell;
  if (!shell) return;

  shell.registerSite({
    collapse: {
      contentContainerXPath: "./div[2]",
      headerXPath: "./div[2]/h4",
      hideFollowingSiblingsOfHeader: true,
      startCollapsed: true,
      toggleCollapsedLabel: "▸",
      toggleExpandedLabel: "▾",
      toggleTitleCollapsed: "Show article",
      toggleTitleExpanded: "Hide article",
      transitionMs: 220,
    },
    controller: {
      afterSyncHandlerName: "monthNamedDateNavigation",
      afterSyncHandlerOptions: {
        monthNames: [
          "january",
          "february",
          "march",
          "april",
          "may",
          "june",
          "july",
          "august",
          "september",
          "october",
          "november",
          "december",
        ],
        pathnamePattern: "^/liveblog-([a-z]+)-(\\d{1,2})-(\\d{4})/?$",
        pathnameTemplate: "/liveblog-{month}-{day}-{year}",
        trailingSlash: true,
      },
    },
    cssVars: {
      "--arc-jk-item-overflow": "visible",
      "--arc-jk-progress-offset": "-24px",
    },
    exportName: "__arcJKTimesOfIsrael",
    feed: {
      defaultProfile: "liveblog",
      profiles: {
        liveblog: {
          container: {
            xpaths: [
              "//div[contains(concat(' ', normalize-space(@class), ' '), ' liveblogdiv ')]",
              "/html/body/div[1]/div/article/div[4]/div/div/div[1]/div",
            ],
          },
          itemId: {
            attributeName: "data-item",
            mode: "attribute",
          },
          items: {
            childTagName: "DIV",
            mode: "direct-children",
          },
          match: {
            requirePermalink: true,
          },
          permalink: {
            hrefIncludes: "/liveblog_entry/",
            selector: 'h4 > a[href*="/liveblog_entry/"]',
          },
        },
      },
    },
    flags: {
      enableAfterSyncHandler: true,
      enableArticleAncestorItems: false,
      enableAttributeItemId: true,
      enableBoundaryIdProgressTracking: false,
      enableBottomJumpRestore: false,
      enableCollapseNonHeaderContent: true,
      enableContainerCandidateSearch: false,
      enableContainerXPathLookup: true,
      enableDirectChildItems: true,
      enableDocumentBottomRestore: true,
      enableFallbackTabSelector: false,
      enableFeedMutationObserver: true,
      enableGlobalScopeFallback: false,
      enableHistoryResync: false,
      enableInlineItemLayoutFixes: true,
      enableInlineRenderer: true,
      enableInteractionOnlyWhenRestoreAllowed: false,
      enableItemMarkerValidation: false,
      enableLoadMoreRestore: false,
      enableMutationResync: false,
      enableNormalizedHrefItemId: false,
      enableOverlayRenderer: false,
      enablePathRouteGate: false,
      enablePendingScopeWhenTabsUnavailable: false,
      enablePermalinkProximityBonus: false,
      enablePermalinkSelection: true,
      enablePermalinkValidation: false,
      enablePrimaryTabProgressBlock: false,
      enableProfileByScopeKey: false,
      enableRegexItemId: false,
      enableRestoreDelay: false,
      enableRestoreMissingItemHandler: true,
      enableRestorePauseAfterGrowth: false,
      enableSingleFixedScope: true,
      enableTabAriaActiveState: false,
      enableTabClickResync: false,
      enableTabContainerAncestorLookup: false,
      enableTabContainerTextMatchLookup: false,
      enableTabContainerXPathLookup: false,
      enableTabbedScope: false,
      enableTabIndicatorActiveState: false,
      enableTabTextColorActiveState: false,
      enableUnknownScopeWhenActiveTabMissing: false,
      enableXPathSnapshotItems: false,
    },
    installFlag: "__arcJKTimesOfIsraelInstalled",
    match: {
      allowSubdomains: false,
      domains: ["timesofisrael.com"],
      pathnamePattern: "^/liveblog-[a-z]+-\\d{1,2}-\\d{4}/?$",
      stripWww: true,
    },
    name: "timesofisrael",
    observer: {
      childList: true,
      containerXPath:
        "//div[contains(concat(' ', normalize-space(@class), ' '), ' liveblogdiv ')]",
      subtree: false,
    },
    render: {
      inlineFixes: {
        checkboxLeft: "var(--arc-jk-progress-offset)",
        checkboxPosition: "absolute",
        checkboxTop: "50%",
        checkboxTransform: "translateY(-50%)",
        itemOverflowImportant: true,
        itemOverflowValue: "visible",
        itemPosition: "relative",
      },
    },
    restore: {
      maxSteps: 240,
      onMissingItemHandlerName: "monthNamedDateSavedPath",
      onMissingItemHandlerOptions: {
        loadMoreButtonXPaths: [
          "/html/body/div[1]/div/article/div[4]/div/div/div[1]/div/div[12]/button",
          "//div[contains(concat(' ', normalize-space(@class), ' '), ' liveblogdiv ')]/div/button",
        ],
        loadMoreClickThrottleMs: 900,
        monthNames: [
          "january",
          "february",
          "march",
          "april",
          "may",
          "june",
          "july",
          "august",
          "september",
          "october",
          "november",
          "december",
        ],
        maxBackDays: 90,
        pathnamePattern: "^/liveblog-([a-z]+)-(\\d{1,2})-(\\d{4})/?$",
        pathnameTemplate: "/liveblog-{month}-{day}-{year}",
        sessionKey: "__arcJKTimesOfIsraelLiveblogRestore__",
        trailingSlash: true,
      },
      readinessRequiresContainer: true,
      startDelayMs: 60,
      stopWhenStuckAtOrAbove: false,
      stuckLimit: 30,
      tickMs: 250,
    },
    scope: {
      fixed: {
        allowsPersistence: true,
        allowsRestore: true,
        key: "liveblog",
        kind: "liveblog",
        label: "Liveblog",
      },
      kind: "liveblog",
    },
    storageKey: "arc-jk-timesofisrael-liveblog-progress-v1",
  });
})();
