(() => {
  const shell = window.__feedScrollerShared__?.shell;
  if (!shell) return;

  shell.registerSite({
    api: {
      aliases: {
        isMoviesActiveNow: "isActiveNow",
      },
    },
    exportName: "__arcJK_X",
    feed: {
      defaultProfile: "timeline",
      profiles: {
        timeline: {
          itemId: {
            mode: "regex-from-anchor-href",
            regex: "/status/(\\d+)",
          },
          items: {
            ancestorSelector: 'div[data-testid="cellInnerDiv"]',
            mode: "article-ancestor",
            requiredDescendantSelector: 'a[href*="/status/"]',
            searchRootSelector: "main",
            selector: "article",
            sortByTop: true,
          },
          match: {
            requirePermalink: false,
          },
          permalink: {
            hrefIncludes: "/status/",
            preferredDescendantBonus: 1000,
            preferredDescendantSelector: "time[datetime]",
            selector: 'a[href*="/status/"]',
          },
        },
      },
    },
    flags: {
      enableAfterSyncHandler: false,
      enableArticleAncestorItems: true,
      enableAttributeItemId: false,
      enableBoundaryIdProgressTracking: true,
      enableBottomJumpRestore: true,
      enableCollapseNonHeaderContent: false,
      enableContainerCandidateSearch: false,
      enableContainerXPathLookup: false,
      enableDirectChildItems: false,
      enableDocumentBottomRestore: false,
      enableFallbackTabSelector: false,
      enableFeedMutationObserver: false,
      enableGlobalScopeFallback: false,
      enableHistoryResync: true,
      enableInlineItemLayoutFixes: false,
      enableInlineRenderer: false,
      enableInteractionOnlyWhenRestoreAllowed: true,
      enableItemMarkerValidation: false,
      enableLoadMoreRestore: false,
      enableMutationResync: true,
      enableNormalizedHrefItemId: false,
      enableOverlayRenderer: true,
      enablePathRouteGate: false,
      enablePendingScopeWhenTabsUnavailable: true,
      enablePermalinkProximityBonus: false,
      enablePermalinkSelection: true,
      enablePermalinkValidation: false,
      enablePrimaryTabProgressBlock: true,
      enableProfileByScopeKey: false,
      enableRegexItemId: true,
      enableRestoreDelay: true,
      enableRestoreMissingItemHandler: false,
      enableRestorePauseAfterGrowth: true,
      enableSingleFixedScope: false,
      enableTabAriaActiveState: true,
      enableTabClickResync: true,
      enableTabContainerAncestorLookup: false,
      enableTabContainerTextMatchLookup: true,
      enableTabContainerXPathLookup: true,
      enableTabbedScope: true,
      enableTabIndicatorActiveState: false,
      enableTabTextColorActiveState: false,
      enableUnknownScopeWhenActiveTabMissing: true,
      enableXPathSnapshotItems: false,
    },
    installFlag: "__arcJKBoostInstalled_X",
    match: {
      allowSubdomains: true,
      domains: ["twitter.com", "x.com"],
    },
    name: "x",
    restore: {
      maxMs: 60000,
      postLoadDelayMs: 320,
      restoreDelayMs: 120,
      startDelayMs: 50,
      stuckLimit: 140,
      tickMs: 120,
    },
    scope: {
      kind: "timeline",
      pendingFallback: {
        allowsPersistence: false,
        allowsRestore: false,
        key: "pending",
        kind: "timeline",
        label: "pending",
      },
      pendingPath: "/home",
      unknownFallback: {
        allowsPersistence: false,
        allowsRestore: false,
        key: "unknown",
        kind: "timeline",
        label: "unknown",
      },
    },
    storageKey: "arc-jk-progress-x-status-v3",
    tabs: {
      activeSources: [{ target: "tab", type: "aria-selected" }],
      container: {
        candidateSelector: "nav",
        labelMatchMode: "all",
        labelMatchTexts: ["for you", "following"],
        minimumCount: 2,
        searchRootSelector: "main",
        xpaths: [
          "/html/body/div[1]/div/div/div[2]/main/div/div/div/div[1]/div/div[1]/div[1]/div/nav/div/div[2]/div",
        ],
      },
      labelSources: [
        {
          key: "span",
          selector: "span",
          text: true,
        },
        {
          key: "self",
          selfText: true,
        },
        {
          attribute: "aria-label",
          key: "aria",
        },
      ],
      minimumCount: 2,
      primaryTabIndex: 0,
      tabSelector: '[role="tab"]',
    },
  });
})();
